# Create working directory;
mkdir -p OUT_CU111_PEPTIDE;
#
# Split input PDB file into segments}
grep -v '^HETATM' hisprophe_only.pdb > OUT_CU111_PEPTIDE/hisprophe_only.pdb ;
grep -v '^HETATM' Cu111_only.pdb > OUT_CU111_PEPTIDE/Cu111_only.pdb ;
# (2) Embed the psfgen commands in tile script
./psfgen << ENDMOL ;
 
#
# Read topology file
topology top_all22_prot_metals.inp 
#
# Build protein segment
pdbalias residue HIS HSE
segment PEP {
#patch NTER
pdb OUT_CU111_PEPTIDE/hisprophe_only.pdb 
#}
segment CU {
#first none
#last none
pdb OUT_CU111_PEPTIDE/Cu111_only.pdb 
}
#
#
# Read protein and metal coordinates from PDB files
coordpdb OUT_CU111_PEPTIDE/hisprophe_only.pdb PEP  ;#segment name cannot be longer than 4 letters 
coordpdb OUT_CU111_PEPTIDE/Cu111_only.pdb CU
#
# (7) Build water segment
#segment SOLV {
# auto none 
# pdb OUT_AG111_H2O_PEPTIDE/h2o_only.pdb 
#}
#
# (8) Read water coordinates from PDB file
#coordpdb OUT_AG111_H2O_PEPTIDE/h2o_only.pdb SOLV 
#
# (9) Guess missing coordinates
guesscoord 
#
# (10) Write structure and coordinate files
writepsf OUT_CU111_PEPTIDE/Cu111_hisprophe.psf 
writepdb OUT_CU111_PEPTIDE/Cu111_hisprophe.pdb 
#
# End of psfgen commands
ENDMOL 
