#######################################################
#example SGE batch script for a plain MPI program using
#512 cores (16 nodes x 32 cores per node) with 32 MPI 
#tasks per node
#executed under the intel runtime 
#######################################################

## run in /bin/bash
#$ -S /bin/bash
## do not join stdout and stderr
#$ -j n
## name of the job
#$ -N D000002324
## execute job from the current working directory
#$ -cwd
## do not send mail
#$ -m n
## request 64 cores. The value must be a multiple of 32
#$ -pe impi_hydra 64
## run for 300 minutes
#$ -l h_rt=05:00:00



module purge
module load intel/17.0 impi/2017.2 mkl/2017 anaconda/2_4.2.0
module list

source activate 27rdkit-env
export PYTHONPATH=$PYTHONPATH:/u/damaksim/soft/fafoom-dev
export PATH=$PATH:/eos/u/damaksim/soft/fhi-aims.160328_3/bin
export LD_LIBRARY_PATH="/afs/@cell/common/soft/intel/ics2017.1/17.0/linux/mkl/lib/intel64/:$LD_LIBRARY_PATH"

time python /eos/scratch/damaksim/fafoom_test/ga.py parameters_aims.txt
