# Create working directory;
mkdir -p OUT_CU111_PEPTIDE;
#
# Split input PDB file into segments}
#grep -v '^HETATM' hisprophe_only.pdb > OUT_CU111_PEPTIDE/hisprophe_only.pdb ;
#grep -v '^HETATM' Cu111_only.pdb > OUT_CU111_PEPTIDE/Cu111_only.pdb ;
# (2) Embed the psfgen commands in tile script
./psfgen << ENDMOL ;
 
#
# Read topology file
topology top_all22_prot_metals.inp 
#
# Build protein segment
pdbalias residue HIS HSP
segment MOL {
first NTER
last  CTER
pdb mol.pdb 
#}
segment CU {
#first none
#last none
pdb surrounding.pdb 
}
#patch NTER MOL:1
#patch CTER MOL:3 
#
#
# Read protein and metal coordinates from PDB files
coordpdb mol.pdb MOL  ;#segment name cannot be longer than 4 letters 
coordpdb surrounding.pdb CU
#
# (7) Build water segment
#segment SOLV {
# auto none 
# pdb OUT_AG111_H2O_PEPTIDE/h2o_only.pdb 
#}
#
# (8) Read water coordinates from PDB file
#coordpdb OUT_AG111_H2O_PEPTIDE/h2o_only.pdb SOLV 
#
# (9) Guess missing coordinates
guesscoord 
#
# (10) Write structure and coordinate files
writepsf all.psf 
writepdb all_again.pdb 
#
# End of psfgen commands
#ENDMOL 